In [2]:
 conda install -c conda-forge gmaps

Collecting package metadata (current_repodata.json): done
Solving environment: done

## Package Plan ##

  environment location: /Users/ijcm122/opt/anaconda3

  added / updated specs:
    - gmaps


The following packages will be downloaded:

    package                    |            build
    ---------------------------|-----------------
    conda-4.9.2                |   py38h50d1736_0         3.1 MB  conda-forge
    geojson-2.5.0              |             py_0          15 KB  conda-forge
    gmaps-0.9.0                |             py_0         1.7 MB  conda-forge
    python_abi-3.8             |           1_cp38           4 KB  conda-forge
    ------------------------------------------------------------
                                           Total:         4.8 MB

The following NEW packages will be INSTALLED:

  geojson            conda-forge/noarch::geojson-2.5.0-py_0
  gmaps              conda-forge/noarch::gmaps-0.9.0-py_0
  python_abi         conda-forge/osx-64::python_abi-3.8-1_cp38

The following packages will be SUPERSEDED by a higher-priority channel:

  conda               pkgs/main::conda-4.9.2-py38hecd8cb5_0 --> conda-forge::conda-4.9.2-py38h50d1736_0



Downloading and Extracting Packages
python_abi-3.8       | 4 KB      | ##################################### | 100%
conda-4.9.2          | 3.1 MB    | ##################################### | 100%
gmaps-0.9.0          | 1.7 MB    | ##################################### | 100%
geojson-2.5.0        | 15 KB     | ##################################### | 100%
Preparing transaction: done
Verifying transaction: done
Executing transaction: done

Note: you may need to restart the kernel to use updated packages.

In [3]:
%matplotlib inline

In [19]:
pip install pycity-base

Collecting pycity-base
  Downloading pycity_base-0.3.1.tar.gz (17.8 MB)
     |████████████████████████████████| 17.8 MB 4.9 MB/s eta 0:00:01
Requirement already satisfied: numpy in ./opt/anaconda3/lib/python3.8/site-packages (from pycity-base) (1.19.2)
Requirement already satisfied: matplotlib in ./opt/anaconda3/lib/python3.8/site-packages (from pycity-base) (3.3.2)
Requirement already satisfied: pandas in ./opt/anaconda3/lib/python3.8/site-packages (from pycity-base) (1.1.3)
Requirement already satisfied: pytest in ./opt/anaconda3/lib/python3.8/site-packages (from pycity-base) (0.0.0)
Requirement already satisfied: xlrd in ./opt/anaconda3/lib/python3.8/site-packages (from pycity-base) (1.2.0)
Requirement already satisfied: networkx in ./opt/anaconda3/lib/python3.8/site-packages (from pycity-base) (2.5)
Processing ./Library/Caches/pip/wheels/74/79/e5/72ca71c1054b35e5ef31bd8762bc90f13cf890c5f9f1e52e76/richardsonpy-0.2.1-py3-none-any.whl
Collecting uesgraphs
  Using cached uesgraphs-0.6.4-py3-none-any.whl (36 kB)
Requirement already satisfied: python-dateutil>=2.1 in ./opt/anaconda3/lib/python3.8/site-packages (from matplotlib->pycity-base) (2.8.1)
Requirement already satisfied: certifi>=2020.06.20 in ./opt/anaconda3/lib/python3.8/site-packages (from matplotlib->pycity-base) (2020.6.20)
Requirement already satisfied: pillow>=6.2.0 in ./opt/anaconda3/lib/python3.8/site-packages (from matplotlib->pycity-base) (8.0.1)
Requirement already satisfied: cycler>=0.10 in ./opt/anaconda3/lib/python3.8/site-packages (from matplotlib->pycity-base) (0.10.0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.3 in ./opt/anaconda3/lib/python3.8/site-packages (from matplotlib->pycity-base) (2.4.7)
Requirement already satisfied: kiwisolver>=1.0.1 in ./opt/anaconda3/lib/python3.8/site-packages (from matplotlib->pycity-base) (1.3.0)
Requirement already satisfied: pytz>=2017.2 in ./opt/anaconda3/lib/python3.8/site-packages (from pandas->pycity-base) (2020.1)
Requirement already satisfied: attrs>=17.4.0 in ./opt/anaconda3/lib/python3.8/site-packages (from pytest->pycity-base) (20.3.0)
Requirement already satisfied: iniconfig in ./opt/anaconda3/lib/python3.8/site-packages (from pytest->pycity-base) (1.1.1)
Requirement already satisfied: packaging in ./opt/anaconda3/lib/python3.8/site-packages (from pytest->pycity-base) (20.4)
Requirement already satisfied: pluggy<1.0,>=0.12 in ./opt/anaconda3/lib/python3.8/site-packages (from pytest->pycity-base) (0.13.1)
Requirement already satisfied: py>=1.8.2 in ./opt/anaconda3/lib/python3.8/site-packages (from pytest->pycity-base) (1.9.0)
Requirement already satisfied: toml in ./opt/anaconda3/lib/python3.8/site-packages (from pytest->pycity-base) (0.10.1)
Requirement already satisfied: decorator>=4.3.0 in ./opt/anaconda3/lib/python3.8/site-packages (from networkx->pycity-base) (4.4.2)
Collecting pyproj
  Using cached pyproj-3.0.0.post1-cp38-cp38-macosx_10_9_x86_64.whl (7.4 MB)
Collecting shapely
  Using cached Shapely-1.7.1-cp38-cp38-macosx_10_9_x86_64.whl (1.0 MB)
Requirement already satisfied: nose in ./opt/anaconda3/lib/python3.8/site-packages (from uesgraphs->pycity-base) (1.3.7)
Collecting pytest-mpl
  Using cached pytest_mpl-0.12-py3-none-any.whl (13 kB)
Requirement already satisfied: six>=1.5 in ./opt/anaconda3/lib/python3.8/site-packages (from python-dateutil>=2.1->matplotlib->pycity-base) (1.15.0)
Building wheels for collected packages: pycity-base
  Building wheel for pycity-base (setup.py) ... done
  Created wheel for pycity-base: filename=pycity_base-0.3.1-py3-none-any.whl size=18265463 sha256=a64b636774ed6a7bf2425c78e6da4aab49b2a64a869a290842ece8ecb5bf5cd7
  Stored in directory: /Users/ijcm122/Library/Caches/pip/wheels/dd/d0/d6/f87d6b0eff338d9d5a7cd8712ba00597db68e4f9274a9a7d42
Successfully built pycity-base
Installing collected packages: richardsonpy, pyproj, shapely, pytest-mpl, uesgraphs, pycity-base
Successfully installed pycity-base-0.3.1 pyproj-3.0.0.post1 pytest-mpl-0.12 richardsonpy-0.2.1 shapely-1.7.1 uesgraphs-0.6.4
Note: you may need to restart the kernel to use updated packages.

In [21]:

# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os
import gmaps.datasets

In [22]:

weather_data = pd.read_csv("https://media.githubusercontent.com/media/ijcm122/UCF-LKM-DATA-PT-12-2020-U-C/main/Homework/06-Python-APIs/Instructions/output_data/cities.csv")
weather_data

,City_ID,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
0,0,ostrovnoy,2,RU,1558378754,72,68.05,39.51,37.50,7.16
1,1,mahebourg,75,MU,1558378503,74,-20.41,57.70,78.80,11.41
2,2,qaanaaq,25,GL,1558378755,73,77.48,-69.36,22.20,2.37
3,3,zhuhai,0,CN,1558378755,39,40.71,112.04,44.60,4.47
4,4,cape town,20,ZA,1558378755,76,-33.93,18.42,55.99,8.05
...,...,...,...,...,...,...,...,...,...,...
543,543,yabrud,0,SY,1558378840,32,33.97,36.66,80.60,8.05
544,544,paraiso,5,MX,1558378898,4,24.01,-104.61,84.20,16.11
545,545,veraval,0,FR,1558378898,62,49.65,0.71,61.00,8.05
546,546,novyy urgal,100,RU,1558378899,93,51.07,132.56,49.74,2.68
547,547,tongren,4,CN,1558378899,64,27.72,109.18,55.86,2.84

In [74]:
# Place latitude and longitude variables in locations
locations = weather_data[["Lat", "Lng"]]

# Place Humidity variable
humidity = weather_data["Humidity"]

In [76]:
# Create Heatmap
fig = gmaps.figure(center=(46.0, -5.0), zoom_level=2)
max_intensity = np.max(humidity)

# Create the heat layer of the map 
heat_layer = gmaps.heatmap_layer(locations, weights = humidity, dissipating=False, max_intensity=100, point_radius=3)

# Add a additional layer
fig.add_layer(heat_layer)

# Display figure
fig

Figure(layout=FigureLayout(height='420px'))

In [77]:
#drop null values null 
#convert degrees to Fahrenheit from Kelvin
#accumulate to run multiple times 
citi_weather['Max Temp'] = (citi_weather['Max Temp'] - 275.13)* 9/5 + 32

#variables: 70 < max temp < 85, cloudiness < 7, wind speed < 5
vacay_city = citi_weather.loc[(citi_weather['Max Temp'] > 70) 
                             & (citi_weather['Max Temp'] < 85)
                             & (citi_weather['Cloudiness'] < 7)
                             & (citi_weather['Wind Speed'] < 5)
                             ]
#convert back to Kelvin from Fahrenheit
citi_weather['Max Temp'] = (citi_weather['Max Temp'] - 32)* 5/9 + 275.13

In [78]:
# Narrow down the cities with wind speed less than 10 mph, cloudiness equals to 0 and max temp between 60 and 80
narrowed_city_df = weather_data.loc[(weather_data["Wind Speed"] <= 10) & (weather_data["Cloudiness"] == 0) & \
                                   (weather_data["Max Temp"] >= 70) & (weather_data["Max Temp"] <= 80)].dropna()

narrowed_city_df

,City_ID,City,Cloudiness,Country,Date,Humidity,Lat,Lng,Max Temp,Wind Speed
70,70,ponta do sol,0,BR,1558378767,57,-20.63,-46.00,73.68,5.32
88,88,cidreira,0,BR,1558378770,66,-30.17,-50.22,76.56,5.50
138,138,morondava,0,MG,1558378780,69,-20.30,44.28,79.08,9.06
139,139,vaini,0,IN,1558378780,88,15.34,74.49,78.90,1.59
176,176,nador,0,MA,1558378499,40,35.17,-2.93,75.20,6.93
297,297,mogok,0,MM,1558378844,51,22.92,96.51,72.24,2.77
444,444,birjand,0,IR,1558378880,26,32.86,59.22,71.60,9.17

In [61]:
# Create a hotel_df
hotel_df = narrowed_city_df.loc[:,["City","Country", "Lat", "Lng"]]

# Put "Hotel Name" column to the DataFrame.
hotel_df["Hotel Name"] = ""

# Print the result
hotel_df

             City Country    Lat    Lng Hotel Name
70   ponta do sol      BR -20.63 -46.00
88       cidreira      BR -30.17 -50.22
138     morondava      MG -20.30  44.28
139         vaini      IN  15.34  74.49
176         nador      MA  35.17  -2.93
297         mogok      MM  22.92  96.51
444       birjand      IR  32.86  59.22

In [62]:
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"

params = {"type" : "hotel",
          "keyword" : "hotel",
          "radius" : 5000}

In [73]:
base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
params = {
    "location": "0, 0",
    "rankby": "distance",
    "type": "lodging",
    "locationbias": 5000,
    "keyword": "hotel",
   
}
# use iterrows to iterate through pandas dataframe
for index, row in hotel_df.iterrows():
  
# add appropriate coordinates to params
    this_lat = row['Lat']
    this_lng = row['Lng']
    this_place = f'{this_lat},{this_lng}'
    
    params['location'] = this_place
# assemble url and make API request
    city_name = row['City']
    print(f"Retrieving Results for Index {index}: {city_name}.")
    response = requests.get(base_url, params=params).json()
    
#    extract results
    results = response['results']
    try:
        first_name = results[0]['name']
        print(json.dumps(first_name, indent=4))
        hotel_df.loc[index, "Hotel Name"]= first_name
        
    except (KeyError, IndexError):
        print("Missing field/result... skipping.")

    print("------------")

Retrieving Results for Index 70: ponta do sol.
Missing field/result... skipping.
------------
Retrieving Results for Index 88: cidreira.
Missing field/result... skipping.
------------
Retrieving Results for Index 138: morondava.
Missing field/result... skipping.
------------
Retrieving Results for Index 139: vaini.
Missing field/result... skipping.
------------
Retrieving Results for Index 176: nador.
Missing field/result... skipping.
------------
Retrieving Results for Index 297: mogok.
Missing field/result... skipping.
------------
Retrieving Results for Index 444: birjand.
Missing field/result... skipping.
------------

In [69]:
#Using the template to add hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel Name}</dd>
<dt>City</dt><dd>{City}</dd>
<dt>Country</dt><dd>{Country}</dd>
</dl>
"""
#DataFrame 
hotel_info = [info_box_template.format(**row) for index, row in hotel_df.iterrows()]
locations = hotel_df[["Lat", "Lng"]]

In [67]:
# Add layer ontop of heat map
markers = gmaps.marker_layer(locations,
    info_box_content=[f"Hotel loc: {rate}" for rate in hotel_info])
fig.add_layer(markers)
# Display
fig

Figure(layout=FigureLayout(height='420px'))